### ISSUE TITLE
Page displaying a collection

### ISSUE THREAD

**Issue by rtroncy** [MeMAD-project/explorer#1]
In the MeMAD Knowledge Graph, we have collections such as Strömsö (https://data.memad.eu/yle/stromso) or Urheiluruutu (https://data.memad.eu/yle/urheiluruutu) which is a sports program.

The visualization of collection pages should be improved, looking at https://explorer.memad.eu/collections/yle%252Fstromso and https://explorer.memad.eu/collections/yle%252Furheiluruutu? In particular:

- Why does the title of the page duplicate the label of the collection?

- We could display the count of items in a given collection as it is done in the search pages (e.g. https://explorer.memad.eu/browse?type=collections&q=Str%C3%B6&page=1 or https://explorer.memad.eu/browse?type=collections&q=Urheiluruutu&page=1)

- How the Explorer URI are created for collections. I'm questioning the presence of %252F

**Comment by ehrhart** [comment]
> Why does the title of the page duplicate the label of the collection?

Because the predicate used for the label appears twice with the same value in the KG for these two collections, as you can see on the faceted browser.

```turtle
<http://data.memad.eu/yle/stromso> ebucore:title "Str\u00F6ms\u00F6 ", "Str\u00F6ms\u00F6 " .
```

In the meantime, I have improved the display of multiple labels by separating them with a comma. (D2KLab/explorer@6a3ddb8)

> We could display the count of items in a given collection as it is done in the search pages (e.g. https://explorer.memad.eu/browse?type=collections&q=Str%C3%B6&page=1 or https://explorer.memad.eu/browse?type=collections&q=Urheiluruutu&page=1)

Sounds good, I will add it.

> How the Explorer URI are created for collections. I'm questioning the presence of %252F

Some improvements have been made to links encoding. `https://explorer.memad.eu/collections/yle%252Fstromso` should now appear as https://explorer.memad.eu/collections/yle/stromso

**Comment by rtroncy** [comment]
@Siliam Should we open an issue on the [rdf-converter repo](https://github.com/MeMAD-project/rdf-converter) for this issue of duplicated labels?

**Comment by Siliam** [comment]
As far as I can tell, it's not a duplicate, but the two strings correspond to the title with two different language tags (in metadata, `FI_TITLE` and `SE_TITLE`). I think this could be handled from the explorer side, right?

**Comment by rtroncy** [comment]
OK @Siliam ... but are the strings language tagged? It seems not. Doing a DESCRIBE on `<http://data.memad.eu/yle/stromso>` returns:

`<http://data.memad.eu/yle/stromso> ebucore:title "Str\u00F6ms\u00F6 " , "Str\u00F6ms\u00F6" .`

Note that the first string has an extra space that should probably not be there and the language tags `@fi` and `@sv` should be added so that a client can decide which language to display. Do you agree?

**Comment by ehrhart** [comment]
Collection items count has been added by https://github.com/D2KLab/explorer/commit/7d14fede8d47fe44d30c48a186e5b57b20c07ef6.

Regarding the untagged labels duplicates, this isn't directly related to the Explorer. Closing this issue.
